/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp com.example.servicetestAdapter.xml -i servicetest.h -a valueadaptor
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef VALUEADAPTOR_H
#define VALUEADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.example.servicetest.ValueAdaptor
 */
class ValueAdaptorAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.example.servicetest.ValueAdaptor")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.example.servicetest.ValueAdaptor\">\n"
"    <method name=\"value\">\n"
"      <arg direction=\"out\" type=\"i\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    ValueAdaptorAdaptor(QObject *parent);
    virtual ~ValueAdaptorAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    int value();
Q_SIGNALS: // SIGNALS
};

#endif
