/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp com.example.servicetestAdapter.xml -i servicetest.h -a valueadaptor
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "valueadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class ValueAdaptorAdaptor
 */

ValueAdaptorAdaptor::ValueAdaptorAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

ValueAdaptorAdaptor::~ValueAdaptorAdaptor()
{
    // destructor
}

int ValueAdaptorAdaptor::value()
{
    // handle method call com.example.servicetest.ValueAdaptor.value
    int out0;
    QMetaObject::invokeMethod(parent(), "value", Q_RETURN_ARG(int, out0));
    return out0;
}

